image bg ch4docupstairs1 = "ch4docupstairs1"
image bg ch4docupstairs2 = "ch4docupstairs2"
image bg ch4docupstairs3 = "ch4docupstairs3"
image bg ch4docupstairs4 = "ch4docupstairs4"
image bg ch4docupstairs5 = "ch4docupstairs5"
image bg ch4docupstairs6 = "ch4docupstairs6"
image bg ch4docupstairs7 = "ch4docupstairs7"
image bg ch4docupstairs8 = "ch4docupstairs8"
image bg ch4docupstairs9 = "ch4docupstairs9"
image bg ch4docupstairs10 = "ch4docupstairs10"
image bg ch4docupstairs11 = "ch4docupstairs11"
image bg ch4docupstairs12 = "ch4docupstairs12"
image bg ch4docupstairs13 = "ch4docupstairs13"
image bg ch4docupstairs14 = "ch4docupstairs14"
image bg ch4docupstairs15 = "ch4docupstairs15"
image bg ch4docupstairs16 = "ch4docupstairs16"
image bg ch4docupstairs17 = "ch4docupstairs17"
image bg ch4docupstairs18 = "ch4docupstairs18"
image bg ch4docupstairs19 = "ch4docupstairs19"
image bg ch4docupstairs20 = "ch4docupstairs20"
image bg ch4docupstairs21 = "ch4docupstairs21"
image bg ch4docupstairs22 = "ch4docupstairs22"
image bg ch4docupstairs23 = "ch4docupstairs23"
image bg ch4docupstairs24 = "ch4docupstairs24"
image bg ch4docupstairs25 = "ch4docupstairs25"
image bg ch4docupstairs26 = "ch4docupstairs26"
image bg ch4docupstairs27 = "ch4docupstairs27"
image bg ch4docupstairs28 = "ch4docupstairs28"
image bg ch4docupstairs29 = "ch4docupstairs29"
image bg ch4docupstairs30 = "ch4docupstairs30"
image bg ch4docupstairs31 = "ch4docupstairs31"
image bg ch4docupstairs32 = "ch4docupstairs32"
image bg ch4docupstairs33 = "ch4docupstairs33"
image bg ch4docupstairs34 = "ch4docupstairs34"
image bg ch4docupstairs35 = "ch4docupstairs35"
image bg ch4docupstairs36 = "ch4docupstairs36"
image bg ch4docupstairs37 = "ch4docupstairs37"
image bg ch4docupstairs38 = "ch4docupstairs38a"
image bg ch4docupstairs39 = "ch4docupstairs39a"
image bg ch4docupstairs40 = "ch4docupstairs40a"
image bg ch4docupstairs41 = "ch4docupstairs41a"
image bg ch4docupstairs42 = "ch4docupstairs42a"
image bg ch4docupstairs43 = "ch4docupstairs43"
image bg ch4docupstairs44 = "ch4docupstairs44"
image bg ch4docupstairs45 = "ch4docupstairs45"
image bg ch4docupstairs46 = "ch4docupstairs46"
image bg ch4docupstairs47 = "ch4docupstairs47"
image bg ch4docupstairs48 = "ch4docupstairs48"
image bg ch4docupstairs49 = "ch4docupstairs49"
image bg ch4docupstairs50 = "ch4docupstairs50"
image bg ch4docupstairs51 = "ch4docupstairs51"
image bg ch4docupstairs52 = "ch4docupstairs52"
image bg ch4docupstairs53 = "ch4docupstairs53"
image bg ch4docupstairs54 = "ch4docupstairs54"
image bg ch4docupstairs55 = "ch4docupstairs55"
image bg ch4docupstairs56 = "ch4docupstairs56"
image bg ch4docupstairs57 = "ch4docupstairs57"
image bg ch4docupstairs58 = "ch4docupstairs58"
image bg ch4docupstairs59 = "ch4docupstairs59"
image bg ch4docupstairs60 = "ch4docupstairs60"
image bg ch4docupstairs61 = "ch4docupstairs61"
image bg ch4docupstairs62 = "ch4docupstairs62"
image bg ch4docupstairs63 = "ch4docupstairs63"
image bg ch4docupstairs64 = "ch4docupstairs64"
image bg ch4docupstairs65 = "ch4docupstairs65"
image bg ch4docupstairs66 = "ch4docupstairs66"
image bg ch4docupstairs67 = "ch4docupstairs67"
image bg ch4docupstairs68 = "ch4docupstairs68"
image bg ch4docupstairs69 = "ch4docupstairs69"
image bg ch4docupstairs70 = "ch4docupstairs70"
image bg ch4docupstairs71 = "ch4docupstairs71"
image bg ch4docupstairs72 = "ch4docupstairs72"
image bg ch4docupstairs73 = "ch4docupstairs73"
image bg ch4docupstairs74 = "ch4docupstairs74"
image bg ch4docupstairs75 = "ch4docupstairs75"
image bg ch4docupstairs76 = "ch4docupstairs76"
image bg ch4docupstairs77 = "ch4docupstairs77"
image bg ch4docupstairs78 = "ch4docupstairs78"
image bg ch4docupstairs79 = "ch4docupstairs79"
image bg ch4docupstairs80 = "ch4docupstairs80"
image bg ch4docupstairs81 = "ch4docupstairs81"
image bg ch4docupstairs82 = "ch4docupstairs82"
image bg ch4docupstairs83 = "ch4docupstairs83"
image bg ch4docupstairs84 = "ch4docupstairs84"
image bg ch4docupstairs85 = "ch4docupstairs85"



label ch4docupstairs:
    play music audio.calm fadein 2.0 fadeout 2.0
    show bg ch4docupstairs1 with dissolve
    p "You have to climb up? Taking the old fashioned girl thing pretty far, aren't you?"
    k "Well, I need to. I don't trust Gus with the elevator."
    p "Gus?"
    show bg ch4docupstairs2 with dissolve
    k "My {i}AI{/i}. He's barely functional with non-medical tasks as is. When he's actually running tests..."
    p "Basic tasks are low priority. That it?"
    k "And getting stuck in an elevator is a nightmare I don't want, thank you very much."
    p "Wait, are you claustrophobic? Then, what about..."
    k "Can we not talk about this?"
    show bg ch4docupstairs3 with dissolve
    p "Cozy. Small, but cozy."
    k "It's all I need. The important stuff is downstairs."
    show bg ch4docupstairs4 with dissolve
    k "So, cards on the table, [p]. Why did you bring her here? Baynard could have fixed her up probably better than I could."
    if "ch4helpdoc" in extraevents:
        p "Better? Doubt that."
        k "Thank you and you're dodging the question."
        p "What she did to your scanner, that was child's play compared to what I saw her do."
        p "Cure for GDS my ass..."
    else:
        p "You might have trouble believing this, but-"
        k "She has crazy mind powers and can make things go boom?"
        p "Wait. What?"
        show bg ch4docupstairs6 with dissolve
        k "I gave her a sedative to calm her down. Started reading her EEG and it went off the chart. Next thing I know. Poof! No more scanner."
        k "I've seen people with some strange abilities... but this?"
    k "So, what now?"
    p "I won't take her to Baynard, not yet, at least."
    show bg ch4docupstairs5 with dissolve
    k "So keep her here."
    p "Absolutely not."
    show bg ch4docupstairs6 with dissolve
    k "Look, that seizure clearly has something to do with her powers and there's no guarantee it won't happen again. If I can figure out how it works..."
    p "Katie..."
    k "You don't trust me with her?"
    p "Of course I trust you. But this is dangerous. I'm not going to let you get involved in this."
    k "It looks like I already am."
    p "Just for tonight and that's because you're the best doctor I know. I don't want to see you get hurt."
    if k_score >= 3:
        k "I think that's my line. Except it doesn't sound so patronizing when I say it."
    else:
        k "I don't want to see me get hurt any more than you, trust me. But it's my call."
    show bg ch4docupstairs7 with dissolve
    p "Katie..."
    k "What about Baynard, [p]? They're going to be wondering where you went."
    p "Let me worry about Baynard."
    show bg ch4docupstairs4 with dissolve
    k "So, you are still thinking of bringing her in?"
    p "My gut says no, it's wrong. My brain screams, Yes, you fool."
    k "Well, your brain's an asshole."
    p "Yeah... Yeah, it is."
    show bg ch4docupstairs8 with dissolve
    k "Look, [p], you look like you could use some sleep. I could too. You can take the chair if you want. It's more comfy than it looks."
    p "Thanks, Doc. You're probably right."
    show bg ch4docupstairs9 with dissolve
    k "Okay, Gus, turn off the lights."
    k "..."
    show bg ch4docupstairs10 with dissolve
    k "Whatever happened to a simple light switch? GUS! Turn off the lights!"
    "Gus" "Processing..."
    "Gus" "Processing..."
    "Gus" "Lights off."
    show bg ch4docupstairs11 with dissolve
    p "You might want to upgrade that. You know, I have some old phones from the twenties in a box back home. They can't be worse..."
    k "Don't you start. You try doing high-end work with a decade-old AI and tell me how it goes."
    show bg ch4docupstairs12 with dissolve
    k "Do you need a blanket or anything?"
    p "Nah, Doc, I'm good."
    show bg ch4docupstairs13 with dissolve
    k "Okay, get some sleep. With the beating you took, you need it."
    k "Night!"
    show bg ch4docupstairs14 with hpunch
    p "(Did she fall asleep that fast? Shit... Now what?)"
    $ resetmenu()
    jump ch4docupstairschoices
# Decompiled by unrpyc: https://github.com/CensoredUsername/unrpyc
